[2022-04-07 19:26:19,976] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_posts_answers.bq_create_posts_answers_stack_overflow_data_partitioned_table_task scheduled__2018-03-01T00:00:00+00:00 [queued]>
[2022-04-07 19:26:20,069] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_posts_answers.bq_create_posts_answers_stack_overflow_data_partitioned_table_task scheduled__2018-03-01T00:00:00+00:00 [queued]>
[2022-04-07 19:26:20,070] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:26:20,070] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 19:26:20,070] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:26:21,037] {taskinstance.py:1270} INFO - Executing <Task(BigQueryInsertJobOperator): create_external_posts_answers.bq_create_posts_answers_stack_overflow_data_partitioned_table_task> on 2018-03-01 00:00:00+00:00
[2022-04-07 19:26:21,094] {standard_task_runner.py:52} INFO - Started process 4575 to run task
[2022-04-07 19:26:21,169] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_posts_answers.bq_create_posts_answers_stack_overflow_data_partitioned_table_task', 'scheduled__2018-03-01T00:00:00+00:00', '--job-id', '12995', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmp_gyszpxw', '--error-file', '/tmp/tmpdg58fs1r']
[2022-04-07 19:26:21,196] {standard_task_runner.py:80} INFO - Job 12995: Subtask create_external_posts_answers.bq_create_posts_answers_stack_overflow_data_partitioned_table_task
[2022-04-07 19:26:21,761] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_posts_answers.bq_create_posts_answers_stack_overflow_data_partitioned_table_task scheduled__2018-03-01T00:00:00+00:00 [running]> on host 2c54f2187010
[2022-04-07 19:26:22,054] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_posts_answers.bq_create_posts_answers_stack_overflow_data_partitioned_table_task
AIRFLOW_CTX_EXECUTION_DATE=2018-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2018-03-01T00:00:00+00:00
[2022-04-07 19:26:22,061] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 19:26:22,076] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 19:26:22,090] {bigquery.py:1554} INFO - Inserting job ***_load_to_BigQuery_create_external_posts_answers_bq_create_posts_answers_stack_overflow_data_partitioned_table_task_2018_03_01T00_00_00_00_00_2f3fece1caae2763f504353b8b9ec6e3
[2022-04-07 19:26:22,536] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2153, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2119, in _submit_job
    retry=self.result_retry,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 439, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1560, in insert_job
    job.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1498, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1488, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Could not cast literal "creation_date" to type TIMESTAMP at [1:109]

Location: us-central1
Job ID: airflow_load_to_BigQuery_create_external_posts_answers_bq_create_posts_answers_stack_overflow_data_partitioned_table_task_2018_03_01T00_00_00_00_00_2f3fece1caae2763f504353b8b9ec6e3

[2022-04-07 19:26:22,575] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=load_to_BigQuery, task_id=create_external_posts_answers.bq_create_posts_answers_stack_overflow_data_partitioned_table_task, execution_date=20180301T000000, start_date=20220407T192619, end_date=20220407T192622
[2022-04-07 19:26:22,643] {standard_task_runner.py:98} ERROR - Failed to execute job 12995 for task create_external_posts_answers.bq_create_posts_answers_stack_overflow_data_partitioned_table_task (400 Could not cast literal "creation_date" to type TIMESTAMP at [1:109]

Location: us-central1
Job ID: airflow_load_to_BigQuery_create_external_posts_answers_bq_create_posts_answers_stack_overflow_data_partitioned_table_task_2018_03_01T00_00_00_00_00_2f3fece1caae2763f504353b8b9ec6e3
; 4575)
[2022-04-07 19:26:22,752] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-07 19:26:22,939] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-07 22:19:03,755] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_posts_answers.bq_create_posts_answers_stack_overflow_data_partitioned_table_task scheduled__2018-03-01T00:00:00+00:00 [queued]>
[2022-04-07 22:19:03,816] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_posts_answers.bq_create_posts_answers_stack_overflow_data_partitioned_table_task scheduled__2018-03-01T00:00:00+00:00 [queued]>
[2022-04-07 22:19:03,816] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:19:03,816] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 22:19:03,816] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:19:04,139] {taskinstance.py:1270} INFO - Executing <Task(BigQueryInsertJobOperator): create_external_posts_answers.bq_create_posts_answers_stack_overflow_data_partitioned_table_task> on 2018-03-01 00:00:00+00:00
[2022-04-07 22:19:04,153] {standard_task_runner.py:52} INFO - Started process 6777 to run task
[2022-04-07 22:19:04,184] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_posts_answers.bq_create_posts_answers_stack_overflow_data_partitioned_table_task', 'scheduled__2018-03-01T00:00:00+00:00', '--job-id', '14239', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmp86uxxqkt', '--error-file', '/tmp/tmp9f_sxlp7']
[2022-04-07 22:19:04,185] {standard_task_runner.py:80} INFO - Job 14239: Subtask create_external_posts_answers.bq_create_posts_answers_stack_overflow_data_partitioned_table_task
[2022-04-07 22:19:04,357] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_posts_answers.bq_create_posts_answers_stack_overflow_data_partitioned_table_task scheduled__2018-03-01T00:00:00+00:00 [running]> on host 36107d30f64e
[2022-04-07 22:19:04,486] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_posts_answers.bq_create_posts_answers_stack_overflow_data_partitioned_table_task
AIRFLOW_CTX_EXECUTION_DATE=2018-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2018-03-01T00:00:00+00:00
[2022-04-07 22:19:04,488] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 22:19:04,510] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 22:19:04,590] {bigquery.py:1554} INFO - Inserting job ***_load_to_BigQuery_create_external_posts_answers_bq_create_posts_answers_stack_overflow_data_partitioned_table_task_2018_03_01T00_00_00_00_00_5ed04da20c20ee9ba0a342bc9e3eede0
[2022-04-07 22:19:08,658] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_posts_answers.bq_create_posts_answers_stack_overflow_data_partitioned_table_task, execution_date=20180301T000000, start_date=20220407T221903, end_date=20220407T221908
[2022-04-07 22:19:08,776] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 22:19:08,880] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
